command:
  - gunicorn
  - app:app
env:
  - name: HOME
    value: /app/python/source_code
  - name: DATABRICKS_TOKEN
    valueFrom: DATABRICKS_TOKEN
  - name: ANTHROPIC_MODEL
    value: databricks-claude-opus-4-6
  - name: GEMINI_MODEL
    value: databricks-gemini-3-1-pro
  - name: CODEX_MODEL
    value: databricks-gpt-5-2
  #OPTIONAL: Move to the new Databricks Gateway if you have access (recommended), otherwise it will default to the older endpoint
  - name: DATABRICKS_GATEWAY_HOST
    valueFrom: DATABRICKS_GATEWAY_HOST
  - name: CLAUDE_CODE_DISABLE_AUTO_MEMORY
    value: 0
