command:
  - bash
  - -c
  - "mkdir -p ~/.local/bin && curl https://getmic.ro | bash && mv micro ~/.local/bin/ 2>/dev/null || true && python setup_claude.py && python app.py"
env:
  - name: HOME
    value: /app/python/source_code
  - name: DATABRICKS_HOST
    value: DATABRICKS_HOST
  - name: DATABRICKS_TOKEN
    valueFrom: DATABRICKS_TOKEN
